import re

RULES = {
    r"PETROLEUM|FUEL|GAS|SHELL|EXXON|BP|CHEVRON|PETROL": "Fuel",
    r"CHEMIST|PHARMACY|CVS|WALGREENS|MEDICINE|DRUG|HEALTH|MEDICAL|CLINIC|HOSPITAL|DOCTOR": "Health/Pharmacy",
    r"STORE|MART|GROCERY|WALMART|TARGET|SUPERMARKET|MARKET|FOOD.*STORE|GROCERY.*STORE": "Groceries",
    r"RESTAURANT|CAFE|FOOD|PIZZA|BURGER|MCDONALDS|STARBUCKS|DINING|TEA.*CORNER|SWEET|DHAKA.*SWEET|CORNER|EATERY|DINER|BAKERY|FOOD.*DELIVERY|TAKEOUT|BAR|PUB|GRILL": "Dining",
    r"UBER|CAREEM|TAXI|RIDE|LYFT|TRANSPORT|BUS|TRAIN|RIDESHARE|CAB|METRO|SUBWAY": "Transport",
    r"ELECTRIC|UTILITY|BILL|WATER|GAS|POWER|ENERGY|SNGPL|BILLING|UTILITY.*COMPANY|POWER.*COMPANY|WATER.*COMPANY": "Utilities",
    r"NETFLIX|DRAMA|WEB.*SERIES|MOVIE|MUSIC|SHOW|SUBSCRIPTION|STREAMING|SONG|VIDEO|AUDIO|PODCAST|ENTERTAINMENT|CINEMA|THEATER|CONCERT|GAME|GAMING|SPOTIFY|YOUTUBE|AMAZON.*PRIME|DISNEY|HULU|APPLE.*MUSIC|ITUNES|STEAM|PLAYSTATION|XBOX|NINTENDO|MEDIA|ENTERTAINMENT": "Entertainment",
    r"SHOP|STORE|RETAIL|CLOTHING|ELECTRONICS|MERCHANDISE|DEPARTMENT|MALL|OUTLET|BOUTIQUE": "Shopping",
    r"SCHOOL|COLLEGE|UNIVERSITY|COURSE|BOOK|EDUCATION|TRAINING|LEARNING|ACADEMY|INSTITUTE": "Education",
    r"HOTEL|FLIGHT|VACATION|TOURISM|ACCOMMODATION|TRAVEL|AIRLINE|HOSTEL|RESORT": "Travel",
    r"INSURANCE|PREMIUM|COVERAGE|POLICY": "Insurance",
    r"STOCK|INVESTMENT|SAVINGS|FINANCIAL|BANK|CREDIT|LOAN|MORTGAGE": "Investment",
}

def categorize_transaction(description: str) -> str:
    """Categorize a single transaction description."""
    desc_upper = description.upper()
    
    # Check each rule pattern
    try:
        for pattern, category in RULES.items():
            if re.search(pattern, desc_upper):
                return category
    except Exception as e:
        print(f"Error categorizing transaction: {e}")
        return "Misc"
    
    return "Misc"

print(categorize_transaction("Shaheen Chemist"))


